services:
  - type: web
    name: diaflow-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: diaflow.settings
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: diaflow-db
          property: connectionString
databases:
  - name: diaflow-db
    plan: free
    databaseName: diaflow
